# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\Documentos\Trabajos\Universidad\5toSem\Electronica\Ordinario\Circuitos-embebidos-ordinario\Ordinario caja fuerte.cydsn\Ordinario caja fuerte.cyprj
# Date: Fri, 08 Jan 2021 22:39:03 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\Documentos\Trabajos\Universidad\5toSem\Electronica\Ordinario\Circuitos-embebidos-ordinario\Ordinario caja fuerte.cydsn\TopDesign\TopDesign.cysch
# Project: D:\Documentos\Trabajos\Universidad\5toSem\Electronica\Ordinario\Circuitos-embebidos-ordinario\Ordinario caja fuerte.cydsn\Ordinario caja fuerte.cyprj
# Date: Fri, 08 Jan 2021 22:39:00 GMT
